# Conda packages for my base environment.
#
# Many of these packages come with Anaconda by default.
# I recommend installing the latest Anaconda then do:
#
#   conda update conda
#   conda install --file base.yml
#
ads
anaconda-client
altair
astropy
bibtexparser
black
bokeh
click
conda-build
coverage
coveralls
cython
dask
flake8
flask
h5py
ipympl
ipython
isort
jupyter
jupyterlab
jupytext
line_profiler
matplotlib
memory_profiler
mpl-scatter-density
mypy
nbsphinx
numpy
pandas
pint
pip
proselint
pyarrow
pycodestyle
pympler
pytest
pytest-cov
python-language-server
requests
scipy
sphinx
sphinx_rtd_theme
sympy
tomlkit
twine
xarray
yaml
yt
