# Conda packages for my base environment.
#
# After installing Anaconda/Miniconda:
#
#   conda update conda
#   conda install --file base.yml
#
ads
altair
anaconda-client
astropy
black
bokeh
click
colorcet
conda-build
coverage
coveralls
cython
dask
datashader
doc8
flake8
flask
fortran-magic
graphviz
h5py
holoviews
ipympl
ipython
isort
jinja2
jupyter
jupyterlab
jupytext
line_profiler
matplotlib
memory_profiler
mypy
nbsphinx
nodejs
numba
numpy
pandas
pillow
pint
pip
proselint
pyarrow
pycodestyle
pydocstyle
pylint
pymc3
pympler
pytest
pytest-cov
python-language-server
requests
scikit-image
scikit-learn
scipy
seaborn
snakeviz
sphinx
sphinx_rtd_theme
statsmodels
sympy
tomlkit
tornado
tqdm
twine
vaex
xarray
yaml
yt
