# conda packages
# to install:
#   conda install --file base.yml

anaconda-client
altair
bibtexparser
black
conda-build
coverage
flake8
ipympl
jupytext
line_profiler
mpl-scatter-density
mypy
progressbar2
pytest-cov
python-language-server
sphinx_rtd_theme
yapf
yt
xarray
