# Conda packages for my base environment.
#
# Many of these packages come with Anaconda by default.
# I recommend installing the latest Anaconda then do:
#
#   conda update conda
#   conda install --file base.yml
#
anaconda-client
altair
astropy
bibtexparser
black
bokeh
conda-build
coverage
cython
dask
flake8
flask
h5py
ipympl
ipython
jupyter
jupyterlab
jupytext
line_profiler
matplotlib
memory_profiler
mpl-scatter-density
mypy
numpy
pandas
pip
pyarrow
pycodestyle
pympler
pytest
pytest-cov
python-language-server
requests
scipy
sphinx
sphinx_rtd_theme
sympy
xarray
yaml
yt
