prompt_order = [
    "time",
    "hostname",
    "directory",
    "git_branch",
    "git_state",
    "git_status",
    "conda",
    "env_var",
    "cmd_duration",
    "line_break",
    "jobs",
    "battery",
    "character",
]

[conda]
symbol = "🅒 "

[time]
disabled = false

[hostname]
prefix = "⟪"
suffix = "⟫"
style = "bold blue"
